#!/bin/sh

brightnessLevel=$(cat /sys/class/backlight/acpi_video0/actual_brightness)
maxBrightness=$(cat /sys/class/backlight/acpi_video0/max_brightness)

#echo $brightnessLevel
#echo $maxBrightness
color1="#2379c2'>"
color2="#2379c2'>"
color2="#2379c2'>"
color3="#2379c2'>"
color4="#2379c2'>"
color5="#2379c2'>"
color6="#2379c2'>"
color7="#2379c2'>"
color8="#2379c2'>"
col="<span color='"
end="</span>"

case $brightnessLevel in
        0)      notify-send "Brightness:" "$col$color1•$end•••••••••••••••";;
        1)      notify-send "Brightness:" "$col$color1••$end••••••••••••••";;
        2)      notify-send "Brightness:" "$col$color2•••$end•••••••••••••";;
        3)      notify-send "Brightness:" "$col$color2••••$end••••••••••••";;
        4)      notify-send "Brightness:" "$col$color3•••••$end•••••••••••";;
        5)      notify-send "Brightness:" "$col$color3••••••$end••••••••••";;
        6)      notify-send "Brightness:" "$col$color4•••••••$end•••••••••";;
        7)      notify-send "Brightness:" "$col$color4••••••••$end••••••••";;
        8)      notify-send "Brightness:" "$col$color5•••••••••$end•••••••";;
        9)      notify-send "Brightness:" "$col$color5••••••••••$end••••••";;
        10)     notify-send "Brightness:" "$col$color6•••••••••••$end•••••";;
        11)     notify-send "Brightness:" "$col$color6••••••••••••$end••••";;
        12)     notify-send "Brightness:" "$col$color7•••••••••••••$end•••";;
        13)     notify-send "Brightness:" "$col$color7••••••••••••••$end••";;
        14)     notify-send "Brightness:" "$col$color8•••••••••••••••$end•";;
        15)     notify-send "Brightness:" "$col$color8••••••••••••••••$end";;
esac
